"""add cloumn facebook_id and google_id

Revision ID: 61280f3791c1
Revises: f5113818dbf4
Create Date: 2018-08-13 19:59:54.122336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61280f3791c1'
down_revision = 'f5113818dbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###
