"""move chat name to chat permission

Revision ID: aed52717ac26
Revises: da550eab4fba
Create Date: 2018-12-01 23:54:14.356783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed52717ac26'
down_revision = 'da550eab4fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_name_key', 'chats', type_='unique')
    op.drop_column('chats', 'name')
    op.add_column('chats_permission', sa.Column('chat_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats_permission', 'chat_name')
    op.add_column('chats', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('chats_name_key', 'chats', ['name'])
    # ### end Alembic commands ###
