"""added default image for group chat

Revision ID: da550eab4fba
Revises: 5a9d2b2aa480
Create Date: 2018-12-01 11:53:22.275753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da550eab4fba'
down_revision = '5a9d2b2aa480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats_permission', sa.Column('chat_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats_permission', 'chat_image')
    # ### end Alembic commands ###
